//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VISITORSinfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitorinfo
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Visiting { get; set; }
        public string Type_of_ID { get; set; }
        public string ID_Num { get; set; }
        public string Vehicle_No { get; set; }
        public string Contact_No { get; set; }
        public string purpose_of_visiting { get; set; }
        public string Status { get; set; }
        public System.DateTime Checked_In { get; set; }
        public System.DateTime Checked_Out { get; set; }
    }
}
